project(base64 C)
add_library(base64 STATIC  "${BASE64_ROOT}/lib/lib.c" "${BASE64_ROOT}/lib/codec_choose.c")
set(BASE64_CODEC_ARCH "${BASE64_ROOT}/lib/arch")
file(TOUCH "${BASE64_ROOT}/lib/config.h")



set(BASE64_INSTALL_LIB ${PROJECT_BINARY_DIR}/Release/${PROJECT_NAME}.lib)
set(BASE64_SOURCES "${BASE64_CODEC_ARCH}/generic/codec.c")

option(BASE64_HAVE_AVX "" ON)
option(BASE64_HAVE_AVX2 "" ON)
option(BASE64_HAVE_SSE3 "" ON)
option(BASE64_HAVE_SSE41 "" ON)
option(BASE64_HAVE_SSE42 "" ON)
option(BASE64_HAVE_NEON32 "" ON)
option(BASE64_HAVE_NEON64 "" ON)
option(BASE64_OPENMP "openmp accelerate" ON)

set(BASE64_DEFINES -DBASE64_IMPLEMENTS)
if(BASE64_HAVE_AVX)
    list(APPEND BASE64_DEFINES -DHAVE_AVX=1)
    list(APPEND BASE64_SOURCES ${BASE64_CODEC_ARCH}/avx/codec.c)
endif()
if(BASE64_HAVE_AVX2)
    list(APPEND BASE64_DEFINES -DHAVE_AVX2=1)
    list(APPEND BASE64_SOURCES ${BASE64_CODEC_ARCH}/avx2/codec.c)
endif()
if(BASE64_HAVE_SSE3)
    list(APPEND BASE64_DEFINES -DHAVE_SSE3=1)
    list(APPEND BASE64_SOURCES ${BASE64_CODEC_ARCH}/ssse3/codec.c)
endif()
if(BASE64_HAVE_SSE41)
    list(APPEND BASE64_DEFINES -DHAVE_SSE41=1)
    list(APPEND BASE64_SOURCES ${BASE64_CODEC_ARCH}/sse41/codec.c)
endif()
if(BASE64_HAVE_SSE42)
    list(APPEND BASE64_DEFINES -DHAVE_SSE42=1)
    list(APPEND BASE64_SOURCES ${BASE64_CODEC_ARCH}/sse42/codec.c)
endif()
if(BASE64_HAVE_NEON32)
    list(APPEND BASE64_DEFINES -DHAVE_NEON32=1)
    list(APPEND BASE64_SOURCES ${BASE64_CODEC_ARCH}/neon32/codec.c)
endif()
if(BASE64_HAVE_NEON64)
    list(APPEND BASE64_DEFINES -DHAVE_NEON64=1)
    list(APPEND BASE64_SOURCES ${BASE64_CODEC_ARCH}/neon64/codec.c)
endif()
target_compile_definitions(base64 PUBLIC ${BASE64_DEFINES})

if(BASE64_OPENMP)
    target_compile_options(base64 PUBLIC "/openmp")
endif()

target_sources(${PROJECT_NAME} PRIVATE ${BASE64_SOURCES})

install(TARGETS ${PROJECT_NAME}
PUBLIC_HEADER DESTINATION include
RUNTIME DESTINATION bin
LIBRARY DESTINATION lib
ARCHIVE DESTINATION lib)

install(FILES "${BASE64_ROOT}/include/libbase64.h" DESTINATION "${INSTALL_INC_PREFIX}")
