project(base64 C)

option(BASE64_HAVE_AVX "" ON)
option(BASE64_HAVE_AVX2 "" ON)
option(BASE64_HAVE_SSSE3 "" ON)
option(BASE64_HAVE_SSSE41 "" ON)
option(BASE64_HAVE_SSSE42 "" ON)
option(BASE64_OPENMP "openmp accelerate" ON)

set(BASE64_DEFINES -DBASE64_IMPLEMENTS)
if(BASE64_HAVE_AVX)
    list(append BASE64_DEFINES -DHAVE_AVX=1)
endif()
if(BASE64_HAVE_AVX2)
    list(append BASE64_DEFINES -DHAVE_AVX2=1)
endif()
if(BASE64_HAVE_SSSE3)
    list(append BASE64_DEFINES -DHAVE_SSSE3=1)
endif()
if(BASE64_HAVE_SSSE41)
    list(append BASE64_DEFINES -DHAVE_SSSE41=1)
endif()
if(BASE64_HAVE_SSSE42)
    list(append BASE64_DEFINES -DHAVE_SSSE42=1)
endif()

add_library(base64 STATIC "${BASE64_ROOT}/lib/lib.c" "${BASE64_ROOT}/lib/codec_choose.c")
message(${BASE64_DEFINES})
target_compile_definitions(base64 PUBLIC ${BASE64_DEFINES})